export const START_RECORD_REQUEST = 'START_RECORD_REQUEST';
export const START_RECORD_SUCCESS = 'START_RECORD_SUCCESS';
export const START_RECORD_FAILURE = 'START_RECORD_FAILURE';

export const STOP_RECORD_REQUEST = 'STOP_RECORD_REQUEST';
export const STOP_RECORD_SUCCESS = 'STOP_RECORD_SUCCESS';
export const STOP_RECORD_FAILURE = 'STOP_RECORD_FAILURE';

export const CHANGE_SHOW_ITEMS = 'CHANGE_SHOW_ITEMS';

export const CONNECT_REQUEST = 'CONNECT_REQUEST';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_FAILURE = 'CONNECT_FAILURE';

export const GET_PERF_DATA_REQUEST = 'GET_PERF_DATA_REQUEST';
export const GET_PERF_DATA_SUCCESS = 'GET_PERF_DATA_SUCCESS';
export const GET_PERF_DATA_FAILURE = 'GET_PERF_DATA_FAILURE';

export const DETECT_PERF = 'DETECT_PERF';
